---
name: Test-MockRandom
version: 0.9901
author:
  - 'David A Golden <dagolden@cpan.org>'
abstract: |-
  Replaces random number generation with non-random number
  generation
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0.45
  perl: 5.004
provides:
  Test::MockRandom:
    file: lib/Test/MockRandom.pm
    version: 0.9901
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
